### PR TITLE
communication content update

### PR DESCRIPTION
**Pull request by Nat-A-M**
Screenshot 2023-01-09 at 14 55 35

Updates to review screen & 'provide' sentence
Screenshot 2023-01-09 at 15 45 40
Screenshot 2023-01-09 at 15 46 04

### CODE REVIEW

**Comment by Nat-A-M** [comment]
Does the 'provide details' sentence need to be changed to 'Provide details of your ommunication and analytical judgement skills'? Same for the review screen

**Review by dalcJ — CHANGES_REQUESTED** [review]
These look good. There are a couple of other places that the wording also needs updating (task list, example applications etc). If you do a search for 'Communication, analytical and judgement skills' across the prototype and update it should catch everything

**Comment by Nat-A-M** [comment]
> These look good. There are a couple of other places that the wording also needs updating (task list, example applications etc). If you do a search for 'Communication, analytical and judgement skills' across the prototype and update it should catch everything

Ok, it should be all done now. Please let me know if you see any areas that have not been changed.

**Comment by dalcJ** [comment]
> Ok, it should be all done now. Please let me know if you see any areas that have not been changed.

Just a couple more in session-data-defaults, which is where the examples of filled applications are stored.

Screenshot 2023-01-10 at 14 42 57

**Review by dalcJ — APPROVED** [review]

**Pull request merged**
