### PR TITLE
Addition of delete flow

### PR DESCRIPTION
**Pull request by Nat-A-M**
Here is the completed delete flow. Can't merge?
Screenshot 2022-11-18 at 11 45 57
Screenshot 2022-11-18 at 11 40 41

### CODE REVIEW

**Comment by dalcJ** [comment]
@jesseyuen @Nat-A-M after selecting the file and then pressing 'save and continue' the user is taken to another page but the heading is different. Is that expected? I wondered if it was a little confusing and if the user would know they are still in the 'verify your identity' step? 

Screenshot 2022-11-18 at 16 37 32

**Comment by dalcJ** [comment]
Should the back link go the previous page rather than the task list? 

Screenshot 2022-11-18 at 16 35 23

**Comment by dalcJ** [comment]
Should this heading be the same size as used for 'Review your details'? 

Screenshot 2022-11-18 at 16 35 33

**Comment by Nat-A-M** [comment]
> @jesseyuen @Nat-A-M after selecting the file and then pressing 'save and continue' the user is taken to another page but the heading is different. Is that expected? I wondered if it was a little confusing and if the user would know they are still in the 'verify your identity' step?
> 
> Screenshot 2022-11-18 at 16 37 32

Thanks Jackie, I'll change the size of the heading and explore the link you referenced.

**Comment by Nat-A-M** [comment]
> Should this heading be the same size as used for 'Review your details'?
> 
> Screenshot 2022-11-18 at 16 35 33

I have changed the size of the setting to large instead of xl. How does it look? 

Screenshot 2022-11-21 at 12 38 05

**Comment by Nat-A-M** [comment]
> @jesseyuen @Nat-A-M after selecting the file and then pressing 'save and continue' the user is taken to another page but the heading is different. Is that expected? I wondered if it was a little confusing and if the user would know they are still in the 'verify your identity' step?
> 
> Screenshot 2022-11-18 at 16 37 32

When the user clicks 'save and continue' it goes to this screen: 
Screenshot 2022-11-21 at 15 03 32

Is this the screen that you are referring to?

**Comment by dalcJ** [comment]
> When the user clicks 'save and continue' it goes to this screen: Screenshot 2022-11-21 at 15 03 32
> 
> Is this the screen that you are referring to?


Ah sorry, I meant the 'Review your details' heading, I think that should be 'Verify your details' to match the other screens in the section. And then a title above the box 'Your uploaded file' and in the box just the image and the Change | Delete links. Like this: 

Screenshot 2022-11-21 at 16 02 56

**Comment by jesseyuen** [comment]
> Should the back link go the previous page rather than the task list?
> 
> Screenshot 2022-11-18 at 16 35 23

@JackieDAlcorn on all Review screens in the service the back link is "Back to application" as the summary card itself acts as navigational element a way to go to each screen in that section.

**Comment by jesseyuen** [comment]
> > @jesseyuen @Nat-A-M after selecting the file and then pressing 'save and continue' the user is taken to another page but the heading is different. Is that expected? I wondered if it was a little confusing and if the user would know they are still in the 'verify your identity' step?
> > Screenshot 2022-11-18 at 16 37 32
> 
> Thanks Jackie, I'll change the size of the heading and explore the link you referenced.

@JackieDAlcorn @Nat-A-M 

We've opted for a generic page heading on all review screens. The design system suggests "Check your answers before sending your application", in this case we went with "Review your details" which arguably might not work quite as well in this section than on they other sections.

**Pull request merged**
